### 1. 회원가입 (이메일 검증)
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "이초롱",
  "nickname": "짱",
  "email": "0802222@naver.com",
  "password": "test1234@"
}

### 2. 로그인 성공
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test-1-0-1767017720218@test.com",
  "password": "Test1234!@"
}


### 3. 인증코드 전송
POST http://localhost:8080/auth/email/send-verification?email=test-3-0-1767017720218@test.com


### 4. 이메일 확인 후 코드 검증 (예: 123456)
POST http://localhost:8080/auth/email/verify?email=0802222@naver.com&code=808268
